name: KaiWai Deploy to environment

on:
  push:
    branches:
      - '**'
      - '!staging'   # excludes staging

jobs:
  FrontDeploy:
    name: FrontDeploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: deploy to GitHub Pages
        working-directory: ./sample_web
